### PR TITLE
Added Cosmos DB free tier option

### PR DESCRIPTION
**Pull request by namankothari**
## Description
Describe the changes in this PR.

## Related issues
Addresses [issue #].

## Testing
Describe how this change was tested.

### CODE REVIEW

**Comment by brendankowitz** [comment]
Awesome, love the option to deploy a FHIR Server for free :)

image

**Comment by brendankowitz** [comment]
Adding @LTA-Thinking to help validate the freeness

**Comment by LTA-Thinking** [comment]
I have deployed a service with this template and will monitor it over the next few days.

**Pull request merged**
