### PR TITLE
Updates template for automatic SQL schema updates flag

### PR DESCRIPTION
**Pull request by rbans96**
## Description
Updates template for automatic SQL schema updates flag to default it to empty and make mandatory to select either of the value(true/false). The description of the flag is also updated.

## Related issues
Addresses #[AB76233](https://microsofthealth.visualstudio.com/Health/_boards/board/t/Resolute/Stories/?workitem=76233) and addresses #1276  

## Testing
Tested by customizing the template on azure portal

### CODE REVIEW

**Review by CaitlinV39 — COMMENTED** [review]
Should we add in the help text that you should use the schema migration tool if you set to false?

**Comment by CaitlinV39** [comment]
Related to #1297

**Comment by brendankowitz** [comment]
Does this also effect docker container template?

**Comment by rbans96** [comment]
> Does this also effect docker container template?

Thanks, updated the docker template as well.

**Review by brendankowitz — APPROVED** [review]

**Pull request merged**
