### PR TITLE
Update Deploy to Azure image link

### PR DESCRIPTION
**Pull request by QuanWanxx**
## Description

In [deployment](https://github.com/Microsoft/fhir-server/blob/main/docs/DefaultDeployment.md#deploying-the-fhir-server-template) page, **Deploy to Azure** button is crush from my side due to the security certificate error, the newest Azure document on [Deploy on github](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-azure-button) recommends to use **https://aka.ms/deploytoazurebutton** as the button image.
 
image

image

## FHIR Team Checklist
- [ ] **Update the title** of the PR to be succinct and less than 50 characters
- [ ] **Add a milestone** to the PR for the sprint that it is merged (i.e. add S47)
- [ ] Tag the PR with the type of update: **Bug**, **Dependencies**, **Enhancement**, or **New-Feature**
- [ ] Tag the PR with Azure API for FHIR if this will release to the Azure API for FHIR managed service (CosmosDB or common code related to service)
- [ ] Tag the PR with Azure Healthcare APIs if this will release to the Azure Healthcare APIs managed service (Sql server or common code related to service)
- [ ] CI is green before merge
- Review [squash-merge requirements](https://github.com/microsoft/fhir-server/blob/master/SquashMergeRequirements.md)

### Semver Change ([docs](https://github.com/microsoft/fhir-server/blob/master/docs/Versioning.md))
Skip

### CODE REVIEW

**Review by LTA-Thinking — APPROVED** [review]

**Comment by CaitlinV39** [comment]
> @CaitlinV39 This change makes the Azure deployment and Azure Gov deployment buttons almost identical. Should we reformat the page to make them more separated? image

I think thats a great idea! We could just add a line of text that says. If you want to deploy to the Azure Government Cloud, use this button instead.

**Comment by QuanWanxx** [comment]
> > @CaitlinV39 This change makes the Azure deployment and Azure Gov deployment buttons almost identical. Should we reformat the page to make them more separated? image
> 
> I think thats a great idea! We could just add a line of text that says. If you want to deploy to the Azure Government Cloud, use this button instead.

Added a text for deploying to Azure gov.

**Comment by QuanWanxx** [comment]
Hi @LTA-Thinking, the ```Deploy R4 site``` in PR build pipeline keep fail after retry for times or trigger another one, can you help to check?

**Review by LTA-Thinking — APPROVED** [review]

**Pull request merged**
