### PR TITLE
Add underlying parsing error to meassage.

### PR DESCRIPTION
**Pull request by Ivanidzo4ka**
## Description
Improve error message in case of parsing of document failed.

## Related issues
Addresses [#1395].

## Testing
TBD

### CODE REVIEW

**Comment by brendankowitz** [comment]
I think there was some history with this also, i.e. it used to give an unhelpful error message when the resourceType property was missing or blank

**Comment by Ivanidzo4ka** [comment]
And solution for that was to hide error message completely and replace it with static message. I prefer to go hybrid route, still have static message indicating it's something wrong during parsing, but also include parsing error, so that can give idea to user what is wrong.

---
In reply to: [720791503](https://github.com/microsoft/fhir-server/pull/1417#issuecomment-720791503) [](ancestors = 720791503)

**Comment by brendankowitz** [comment]
Sounds good. 
One day I'd like to invest more in the lower level parsers like (https://github.com/microsoft/fhir-server/blob/personal/bkowitz/json-pipeline-optimizations/src/Microsoft.Health.Fhir.Shared.Api/Features/Formatters/FhirJsonInputFormatter.cs#L84), but its a bit of a concept shift through the entire pipelines

**Review by brendankowitz — APPROVED** [review]

**Pull request merged**
