### PR TITLE
Alter SQL generator to use INNER JOIN for ReferenceSearchParam

### PR DESCRIPTION
**Pull request by feordin**
## Description
At times with complex FHIR queries, the resulting SQL query is very complex and SQL server can timeout attempting to generate the query plan.  We use an EXISTS clause to link References to the target type, but it reduces the burden on SQL server if we use an INNER JOIN.

This change alters the SQL query generator to use an INNER JOIN for ReferenceSearchParams.

## Related issues
Addresses [issue #2818].

## Testing
This was shown to reproduce with member-match and that test has been added.  Also, the specific query mentioned in #2818 was tested manually, and shown to have a 50% reduction in time to produce a query plan.

## FHIR Team Checklist
- **Update the title** of the PR to be succinct and less than 65 characters
- **Add a milestone** to the PR for the sprint that it is merged (i.e. add S47)
- Tag the PR with the type of update: **Bug**, **Build**, **Dependencies**, **Enhancement**, **New-Feature** or **Documentation**
- Tag the PR with **Open source**, **Azure API for FHIR** (CosmosDB or common code) or **Azure Healthcare APIs** (SQL or common code) to specify where this change is intended to be released.
- [ ] CI is green before merge [Build Status](https://microsofthealthoss.visualstudio.com/FhirServer/_build/latest?definitionId=27&branchName=main) 
- Review [squash-merge requirements](https://github.com/microsoft/fhir-server/blob/master/SquashMergeRequirements.md)

### Semver Change ([docs](https://github.com/microsoft/fhir-server/blob/master/docs/Versioning.md))
Patch|Skip|Feature|Breaking (reason)

### CODE REVIEW

**Comment by SergeyGaluzo** [comment]
Changing from EXISTS to JOIN for M:M tables introduced more ambiguity for SQL. We can use JOIN for queries that work today. We can try it only as last resort for query SQL cannot generate plan for.

**Comment by feordin** [comment]
> Changing from EXISTS to JOIN for M:M tables introduced more ambiguity for SQL, and can have performance impact. 
> I suggest not to use JOIN for queries that work today. We can try it only as last resort for query SQL cannot generate plan for.   

For the query in question, the customer currently is blocked as their query regularly has issues completing the query plan generation.  On my dev box, with no data, it requires about 6 seconds to generate the query plan.  With this change it is reduced to 3 seconds.

I could change this PR to be more targeted and limit the conditions when the JOIN is used.

**Comment by SergeyGaluzo** [comment]
When M:M is involved using JOIN in filtering introduces duplicates in the result set which need to be filtered later. In this respect JOIN is strategically incorrect, because it increases chances  that inefficient plan is generated. Creating "bad" plan faster should not be considered as good.
I don't see another way to deal with this problem besides having 2 paths: 1 - with EXISTS, and 2 - only if #1 fails - JOIN.   

---
In reply to: [1532023315](https://github.com/microsoft/fhir-server/pull/3267#issuecomment-1532023315) [](http://example.com/codeflow?ancestors=1532023315,1532023315)

**Comment by feordin** [comment]
> When M:M is involved using JOIN in filtering introduces duplicates in the result set which need to be filtered later. In this respect JOIN is strategically incorrect, because it increases chances that inefficient plan is generated. Creating "bad" plan faster should not be considered as good. I don't see another way to deal with this problem besides having 2 paths: 1 - with EXISTS, and 2 - only if 1 fails - JOIN.
> 
> In reply to: [1532023315](https://github.com/microsoft/fhir-server/pull/3267#issuecomment-1532023315)

However, in the case of failure, the result is a timeout.  How long do we wait?  How do we distinguish between a long running query, and a query that is still attempting to generate a query plan?

**Comment by SergeyGaluzo** [comment]
That is a good point. 
What we know is that there is a limited number of EXISTS SQL can handle. 
Can't we see how many we are going to add, if it is too many switch to JOINs?

---
In reply to: [1532238689](https://github.com/microsoft/fhir-server/pull/3267#issuecomment-1532238689) [](http://example.com/codeflow?ancestors=1532238689,1532238689)

**Comment by feordin** [comment]
build issues, will close and recreate this PR.

**Pull request closed without merging**
