### PR TITLE
Refactor some code in SqlQueryGenerator

### PR DESCRIPTION
**Pull request by namadabu**
## Description
Pushed all code under each case into separate methods to make the code more readable and easier to navigate.

## Related issues
Addresses [issue #].

## Testing
No functional changes.

## FHIR Team Checklist
- [ ] **Update the title** of the PR to be succinct and less than 50 characters
- [ ] **Add a milestone** to the PR for the sprint that it is merged (i.e. add S47)
- [ ] Tag the PR with the type of update: **Bug**, **Dependencies**, **Enhancement**, or **New-Feature**
- [ ] Tag the PR with **Azure API for FHIR** if this will release to the managed service
- Review [squash-merge requirements](https://github.com/microsoft/fhir-server/blob/master/SquashMergeRequirements.md)

### Semver Change ([docs](https://github.com/microsoft/fhir-server/blob/master/docs/Versioning.md))
Patch|Skip|Feature|Breaking (reason)

### CODE REVIEW

**Comment by Ivanidzo4ka** [comment]
I've merged https://github.com/microsoft/fhir-server/pull/1764, so please update your branch (it's easier to force that update on you, than on author of that PR, sorry.)

**Review by Ivanidzo4ka — APPROVED** [review]
This is a good first step to make code more readable. Thank you!

**Comment by Ivanidzo4ka** [comment]
Maybe it's worth to wait for this PR to be merged: https://github.com/microsoft/fhir-server/pull/1785 I assume merging this refactoring would be quite painful for @rotodd

**Comment by namadabu** [comment]
> Maybe it's worth to wait for this PR to be merged: #1785 I assume merging this refactoring would be quite painful for @rotodd

This PR is targeting my feature branch for now. It does make sense to merge it into main branch though. I will wait for @rotodd's PR to get merged in, pull latest changes from main and push an update to this branch

**Comment by Ivanidzo4ka** [comment]
Oh, sorry, didn't notice target branch is different from main

**Pull request merged**
