### PR TITLE
Skip CosmosDb sort tests

### PR DESCRIPTION
**Pull request by namadabu**
## Description
Update CosmosDb sort tests with SkippableFact/Theory since not all dbs might have those enabled.

## Related issues
Addresses [issue #].

## Testing
Describe how this change was tested.

## FHIR Team Checklist
- [x] **Update the title** of the PR to be succinct and less than 50 characters
- [x] **Add a milestone** to the PR for the sprint that it is merged (i.e. add S47)
- [x] Tag the PR with the type of update: **Bug**, **Dependencies**, **Enhancement**, or **New-Feature**
- [x] Tag the PR with **Azure API for FHIR** if this will release to the managed service
- Review [squash-merge requirements](https://github.com/microsoft/fhir-server/blob/master/SquashMergeRequirements.md)

### Semver Change ([docs](https://github.com/microsoft/fhir-server/blob/master/docs/Versioning.md))
Patch

### CODE REVIEW

**Comment by Ivanidzo4ka** [comment]
>not all dbs might have those enabled

Is there are way to detect in test, or it's purely to skip test via command line?

**Review by rotodd — APPROVED** [review]
Thanks for making this change!

**Comment by brendankowitz** [comment]
> > not all dbs might have those enabled
> 
> Is there are way to detect in test, or it's purely to skip test via command line?

These tests are already detecting support. The attribute needs to be "Skippable" for it to be able to skip, otherwise an error is bubbled up and the test fails instead. See https://github.com/AArnott/Xunit.SkippableFact

**Comment by Ivanidzo4ka** [comment]
> > > not all dbs might have those enabled
> > 
> > 
> > Is there are way to detect in test, or it's purely to skip test via command line?
> 
> @Ivanidzo4ka These tests are already detecting support. The attribute needs to be "Skippable" for it to be able to skip, otherwise an error is bubbled up and the test fails instead. See https://github.com/AArnott/Xunit.SkippableFact

I guess I was looking for this line:
https://github.com/microsoft/fhir-server/blob/a2eb81ddf251555d5cc72ddf568945163875daf9/test/Microsoft.Health.Fhir.Shared.Tests.E2E/Rest/Search/SearchTestsBase.cs#L113

**Pull request merged**
