### PR TITLE
Bug 118017 - 500 due to InvalidCastException

### PR DESCRIPTION
**Pull request by v-ajajvanu**
## Description
Made changes to fix the 500 internal server error issue when we pass payload other than Parameter resource type for Patch operation.

## Related issue
Addresses [issue [AB#118017](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/118017)].

## Testing

PATCH request at URL Patient/123 with payload containing resource of type "Parameters". 
Result -> PATCH Operation succeeded, and attributes got updated.

PATCH request at URL Patient/123 with payload containing resource of type "Bundle". 
Result -> PATCH Operation failed, and status code of 400 Bad Request is returned.

Also, tested other HTTP operations like GET, POST, PUT and DELETE on Patient resource to see everything works as expected.

## FHIR Team Checklist
- **Update the title** of the PR to be succinct and less than 65 characters
- **Add a milestone** to the PR for the sprint that it is merged (i.e. add S47)
- Tag the PR with the type of update: **Bug**, **Build**, **Dependencies**, **Enhancement**, **New-Feature** or **Documentation**
- Tag the PR with **Open source**, **Azure API for FHIR** (CosmosDB or common code) or **Azure Healthcare APIs** (SQL or common code) to specify where this change is intended to be released.
- Tag the PR with **Schema Version backward compatible** or **Schema Version backward incompatible** or **Schema Version unchanged** if this adds or updates Sql script which is/is not backward compatible with the code.
- [ ] CI is green before merge [Build Status](https://microsofthealthoss.visualstudio.com/FhirServer/_build/latest?definitionId=27&branchName=main) 
- Review [squash-merge requirements](https://github.com/microsoft/fhir-server/blob/master/SquashMergeRequirements.md)

### Semver Change ([docs](https://github.com/microsoft/fhir-server/blob/master/docs/Versioning.md))
Patch|Skip|Feature|Breaking (reason)

### CODE REVIEW

**Review by abiisnn — COMMENTED** [review]
Can you please add a test for this scenario?

**Comment by v-ajajvanu** [comment]
> Can you please add a test for this scenario?

@abiisnn We had added test cases for the changes made to fix the 500 due to InvalidCastException issue. If possible, could you please review the same.

**Review by abiisnn — APPROVED** [review]
🌸

**Review by fhibf — COMMENTED** [review]
May we add a new E2E test making sure this change is returning a HTTP400 instead of HTTP500?
It'll be important to ensure that customer's a getting the final response code we want.

**Comment by mikaelweave** [comment]
Closing as #3906 merged this code

**Pull request closed without merging**
