### PR TITLE
Docker readme tweak

### PR DESCRIPTION
**Pull request by gotdan**
Add note about SQL server password requirements, since if not met will lead to failed user creation and a broken server instance

### CODE REVIEW

**Comment by marrobi** [comment]
@gotdan good shout. Expect @hansenms will pick this up.

Interested to know if you found the Docker assets useful, and what was the use case?

Hoping we get some official images soon... as per https://github.com/microsoft/fhir-server/pull/840

**Comment by gotdan** [comment]
@marrobi - I set up the docker instance as part of the dev environment for a FHIR cohort query tool I'm building and apart from running into the password issue it went smoothly and was a great fit for the use case. 

I also noticed that the default resources per bundle config of 500 is too low to handle sample data generated by Synthea (though the error message was clear and this was easy to change). Since loading Synthea data is probably a very common scenario for a test instance of the FHIR server, you may want to consider specifically documenting how to change the limit or raising the default to 1000 resources.

**Comment by brendankowitz** [comment]
@brandonpollett I know you've done some perf testing for bundles, though this is also good feedback in https://github.com/microsoft/fhir-server/pull/885#issuecomment-586314063

**Comment by brendankowitz** [comment]
Thanks for the contribution @gotdan (and @marrobi)!

**Pull request merged**
