### PR TITLE
Auto-update for packages related to 'healthcare-components-1.0.0-master-20200611-1'

### PR DESCRIPTION
**Pull request by MicrosoftHealthService**
Updates package 'Microsoft.Health.Abstractions' to version '1.0.0-master-20200611-1'
Updates package 'Microsoft.Health.Core' to version '1.0.0-master-20200611-1'
Updates package 'Microsoft.Health.Extensions.DependencyInjection' to version '1.0.0-master-20200611-1'
Updates package 'Microsoft.Health.Api' to version '1.0.0-master-20200611-1'
Updates package 'Microsoft.Health.Extensions.BuildTimeCodeGenerator' to version '1.0.0-master-20200611-1'
Updates package 'Microsoft.Health.SqlServer' to version '1.0.0-master-20200611-1'
Updates package 'Microsoft.Health.SqlServer.Api' to version '1.0.0-master-20200611-1'

### CODE REVIEW

**Comment by brendankowitz** [comment]
@rbans96 can you also chery-pick @jackliums's changes from https://github.com/microsoft/fhir-server/pull/1070 into this PR

**Comment by rbans96** [comment]
Closing out the PR as pipeline is broken due to hash conflict error. Created a new PR to upgrade the versions https://github.com/microsoft/fhir-server/pull/1088

**Pull request closed without merging**
