### PR TITLE
Updates capability statements for R4

### PR DESCRIPTION
**Pull request by brendankowitz**

### CODE REVIEW

**Comment by brandonpollett** [comment]
R4 seems to be missing `vread`.

**Comment by jackliums** [comment]
Some of the definitions doesn't look right:

``` json
                        {
                            "name": "identifier",
                            "definition": "http://hl7.org/fhir/SearchParameter/Account-identifier",
                            "type": "date",
                            "documentation": "Account number"
                        },
```

Identifier should not be type of date.

**Comment by brendankowitz** [comment]
@brandonpollett @jackliums anything else seem out of place on this one?

**Comment by jackliums** [comment]
I did a quick scan of the file and they all seemed to be fine now.

**Pull request merged**
