### PR TITLE
Updates package 'Hl7.Fhir.R5' to version '2.0.0-beta2'

### PR DESCRIPTION
**Pull request by MicrosoftHealthService**

### CODE REVIEW

**Comment by LTA-Thinking** [comment]
This has several breaking changes as part of the update.

**Comment by brendankowitz** [comment]
This must be part of https://github.com/microsoft/fhir-server/tree/feature/fhir-net-api-2-0

**Comment by Ivanidzo4ka** [comment]
Shall we close this one if we don't plan to take it? Or it will trigger another similar PR creation and this is why we keep this one?

**Comment by brendankowitz** [comment]
We can close the PR, leave the branch until the 2.0 feature branch is done

**Pull request closed without merging**
