### PR TITLE
Remove control plane

### PR DESCRIPTION
**Pull request by brandonpollett**
## Description
Removes the control plane core project and cosmos db project.

## Testing
All remaining tests pass. 

----
Resolves [AB#68892](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/68892)

### CODE REVIEW

**Comment by johnstairs** [comment]
Can you rename `FhirDataStore : IDataStore` to something like `CosmosDbDataStore`

**Comment by brandonpollett** [comment]
> Can you rename `FhirDataStore : IDataStore` to something like `CosmosDbDataStore`

I updated `FhirDataStore` to `FhirCosmosDataStore`. This name matches with the others in the project in that it starts with `FhirCosmos`.

**Comment by johnstairs** [comment]
> > Can you rename `FhirDataStore : IDataStore` to something like `CosmosDbDataStore`
> 
> I updated `FhirDataStore` to `FhirCosmosDataStore`. This name matches with the others in the project in that it starts with `FhirCosmos`.

I don't think the "FhirCosmos" prefix is that great anymore though. We do have FhirDocumentClient since this is meant to be "our" IDocumentClient implementation, but FhirCosmosDataStore is implementing our own IDataStore interface.

**Comment by johnstairs** [comment]
AddFhirServerExperimentalSqlServer -> AddExperimentalSqlServer?

**Pull request merged**
