### PR TITLE
Auto-update for packages related to 'Microsoft.AspNet'

### PR DESCRIPTION
**Pull request by MicrosoftHealthService**
Updates package 'Microsoft.AspNetCore.Authentication.JwtBearer' to version '3.1.9'
Updates package 'Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation' to version '3.1.9'
Updates package 'Microsoft.Extensions.FileProviders.Embedded' to version '3.1.9'
Updates package 'Microsoft.Extensions.Http' to version '3.1.9'
Updates package 'Microsoft.Extensions.Options.ConfigurationExtensions' to version '3.1.9'
Updates package 'Microsoft.Extensions.Configuration.Json' to version '3.1.9'
Updates package 'Microsoft.Extensions.Hosting.Abstractions' to version '3.1.9'
Updates package 'Microsoft.Extensions.Logging' to version '3.1.9'
Updates package 'Microsoft.Extensions.Logging.Abstractions' to version '3.1.9'
Updates package 'Microsoft.Extensions.Diagnostics.HealthChecks' to version '3.1.9'
Updates package 'Microsoft.AspNetCore.Mvc.NewtonsoftJson' to version '3.1.9'
Updates package 'Microsoft.ApplicationInsights.AspNetCore' to version '2.15.0'
Updates package 'Microsoft.Extensions.Configuration.AzureKeyVault' to version '3.1.9'
Updates package 'Microsoft.Extensions.Logging.ApplicationInsights' to version '2.15.0'
Updates package 'Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions' to version '3.1.9'
Updates package 'Microsoft.AspNetCore.Mvc.Testing' to version '3.1.9'
Updates package 'Microsoft.AspNetCore.TestHost' to version '3.1.9'

### CODE REVIEW

**Review by LTA-Thinking — APPROVED** [review]

**Comment by brendankowitz** [comment]
Runtime 3.1.9 should be using SDK 3.1.403 in global.json

**Comment by brendankowitz** [comment]
We probably need a doc on updating framework versions. There is also a version in the deployment templates that use webdeploy

**Review by brendankowitz — APPROVED** [review]

**Pull request merged**
