### PR TITLE
Added support for multi-platform public images

### LINKED ISSUE #3648: Docker container does not run on Apple silicon
**Describe the bug**
Trying to run the published docker container on an Apple M1 or M1 Max doesn't work. The server seems to start, then freezes. Latest when trying to access http://localhost:8080/metadata, CPU will go to 100%. The container stays in this state. Trying to restart it will throw an exception about corrupted data and invalid memory access. Deleting the container and recreating it will repeat the pattern: on first start it freezes, on subsequent restarts it will print a corrupted data exception.

**FHIR Version?**
R4B

**Data provider?**
SQL Server

**To Reproduce**

Use the `docker-compose.yaml` from the samples directory and run `docker-compose up`. The file is pasted in full below - the only change is pulling the FHIR server's container from Microsoft's container registry instead of building it directly (which doesn't work on Apple Silicon as well).

```
version: "3"
services:
  fhir-api:
    image: "mcr.microsoft.com/healthcareapis/r4b-fhir-server:latest"
    restart: on-failure
    environment:
      FHIRServer__Security__Enabled: "false"
      SqlServer__ConnectionString: "Server=tcp:sql,1433;Initial Catalog=FHIR;Persist Security Info=False;User ID=sa;Password=${SAPASSWORD};MultipleActiveResultSets=False;Connection Timeout=30;TrustServerCertificate=true;"
      SqlServer__AllowDatabaseCreation: "true"
      SqlServer__Initialize: "true"
      SqlServer__SchemaOptions__AutomaticUpdatesEnabled: "true"
      DataStore: "SqlServer"
    ports:     
      - "8080:8080"
    depends_on:
      - sql
  sql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: ${SAPASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
        test: ["CMD", "/opt/mssql-tools/bin/sqlcmd","-U sa -P ${SAPASSWORD} -Q 'SELECT * FROM INFORMATION_SCHEMA.TABLES'"]
        interval: 10s
        timeout: 10s
        retries: 6
```

I tried running the file above on an x86 Ubuntu VM and confirmed that it works just fine there. Server starts without issues.

**Expected behavior**
The server starts normally and can be accessed at http://localhost:8080/metadata.

**Actual behavior**
The server freezes on first attempt, eventually going to 100% CPU and staying in that state. On subsequent restarts, it immediately exits with a corrupted data exception.

### PR DESCRIPTION
**Pull request by mikaelweave**
## Description
Builds and pushes multi-platform images in CI pipeline. This will allow users with ARM (Apple Silicone) machines to run the `fhir-server` containers natively. 

Also part of this PR:
- remove the uneeded compose file that's just building a single container
- 

## Related issues
Fixes #3648. [AB#119514](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/119514)

## Testing
Describe how this change was tested.

## FHIR Team Checklist
- **Update the title** of the PR to be succinct and less than 65 characters
- **Add a milestone** to the PR for the sprint that it is merged (i.e. add S47)
- Tag the PR with the type of update: **Bug**, **Build**, **Dependencies**, **Enhancement**, **New-Feature** or **Documentation**
- Tag the PR with **Open source**, **Azure API for FHIR** (CosmosDB or common code) or **Azure Healthcare APIs** (SQL or common code) to specify where this change is intended to be released.
- Tag the PR with **Schema Version backward compatible** or **Schema Version backward incompatible** or **Schema Version unchanged** if this adds or updates Sql script which is/is not backward compatible with the code.
- [ ] CI is green before merge [Build Status](https://microsofthealthoss.visualstudio.com/FhirServer/_build/latest?definitionId=27&branchName=main) 
- Review [squash-merge requirements](https://github.com/microsoft/fhir-server/blob/master/SquashMergeRequirements.md)

### Semver Change ([docs](https://github.com/microsoft/fhir-server/blob/master/docs/Versioning.md))
Patch|Skip|Feature|Breaking (reason)

### CODE REVIEW

**Review by LTA-Thinking — DISMISSED** [review]

**Comment by mikaelweave** [comment]
Fixed the dockerfile 😄 

CleanShot 2024-04-25 at 13 39 54@2x

**Review by LTA-Thinking — APPROVED** [review]

**Pull request merged**
