### PR TITLE
Adds files for testing C4BB

### PR DESCRIPTION
**Pull request by CaitlinV39**
## Description
Adds some rest files for testing C4BB and getting the system setup with search parameters and profiles

## Related issues
N/A

## Testing
Describe how this change was tested.

## FHIR Team Checklist
[X] **Update the title** of the PR to be succinct and less than 50 characters
[X] **Add a milestone** to the PR for the sprint that it is merged (i.e. add S47)
[X] Tag the PR with the type of update: **Bug**, **Dependencies**, **Enhancement**, or **New-Feature**
[X] Tag the PR with **Azure API for FHIR** if this will release to the managed service
- Review [squash-merge requirements](https://github.com/microsoft/fhir-server/blob/master/SquashMergeRequirements.md)

### Semver Change ([docs](https://github.com/microsoft/fhir-server/blob/master/docs/Versioning.md))
Skip

### CODE REVIEW

**Comment by CaitlinV39** [comment]
@Ivanidzo4ka LMK if this is easier to manage :)

**Comment by Ivanidzo4ka** [comment]
Yeah, it's much easier to operate over C4BB.http file.

I think it's ok in it's current state, but if you willing to spend some more time I would do:

- rename `txt` files to `json` so they can be opened as json files.
- move all resources from C4BB_Sampl_Resources to files, it's a mix bag now of two first resource are in files and rest are in http file.

**Review by Ivanidzo4ka — APPROVED** [review]

**Comment by CaitlinV39** [comment]
@Ivanidzo4ka - I'll fix the json files now but will have to close and recreate :)

On the other piece with being consistent, I'm trying to pass in IDs into the resources so maybe they have to be directly in the http file? Do you know a way around this?

**Pull request closed without merging**
