### PR TITLE
Reduce technical debt

### PR DESCRIPTION
**Pull request by marodev**
## Description

This pull request is _very simple_ and aims to reduce the technical debt. It specifically targets the following rules:

ReSharper:
- "Merge sequential checks in && or || expressions" [rule](https://www.jetbrains.com/help/resharper/MergeSequentialChecks.html)
- "Replace if statement with null-propagating" [rule](https://www.jetbrains.com/help/resharper/UseNullPropagation.html)
- "Convert 'as' expression type check and the following null check into pattern matching" [rule](https://www.jetbrains.com/help/resharper/UsePatternMatching.html)
- "Use string interpolation expression"  [rule](https://www.jetbrains.com/help/resharper/UseStringInterpolation.html)

SonarQube:
- "Any() should be used to test for emptiness" [rule](https://rules.sonarsource.com/java/RSPEC-1155)

## Related issues
n/a

## Testing
As this is a simple pull request without any new feature, I locally build the solution making sure there are no compilation errors.

## FHIR Team Checklist
- [x] **Update the title** of the PR to be succinct and less than 50 characters
- [x] **Add a milestone** to the PR for the sprint that it is merged (i.e. add S47)
- [x] Tag the PR with the type of update: **Bug**, **Dependencies**, **Enhancement**, or **New-Feature**
- [x] Tag the PR with **Azure API for FHIR** if this will release to the managed service
- Review [squash-merge requirements](https://github.com/microsoft/fhir-server/blob/master/SquashMergeRequirements.md)

### Semver Change ([docs](https://github.com/microsoft/fhir-server/blob/master/docs/Versioning.md))
Skip

### CODE REVIEW

**Comment by marodev** [comment]
> This pull request **introduces 1 alert** when merging [9e615b5](https://github.com/microsoft/fhir-server/commit/9e615b5ad3996c66b69bac5d5993677eaa8bd9c7) into [b12aef8](https://github.com/microsoft/fhir-server/commit/b12aef8696fd5b71a299bd2420265138774c3277) - [view on LGTM.com](https://lgtm.com/projects/g/microsoft/fhir-server/rev/pr-94d94295a1ffb2e099f8c496aa98f1230034066f)
> 
> **new alerts:**
> 
> * 1 for Dereferenced variable may be null

fixed.

**Review by Ivanidzo4ka — APPROVED** [review]
:shipit:

**Comment by Ivanidzo4ka** [comment]
Thank you for your contribution @marodev !

**Pull request merged**
