### PR TITLE
Remove sdk in global.json for docker builds.

### PR DESCRIPTION
**Pull request by marrobi**
## Description
Removes the SDK version from `global.json` when building the Docker image

## Related issues
Addresses #802

## Testing
Build works on WSL - however should wait for confirmation that issue is resolved on #802 before merging.

### CODE REVIEW

**Comment by marrobi** [comment]
I've actually worked out if we just remove the pinned SDK version - i.e. remove the SDK from `global.json` the image builds successfully. This also means that future updates to 2.2/new 2.2.x docker images should not break the build.

@hansenms thoughts?

**Comment by hansenms** [comment]
@marrobi I think the problem may be that we don't know what might break in another version. There is now an opportunity to build it in a way that we have not tested.

**Comment by hansenms** [comment]
@brendankowitz could you OK this one?

**Comment by brendankowitz** [comment]
Just wanting to confirm the expected behavior, is having the file with an empty entry here different to just removing this file? 
Are we expecting the docker container to build with the latest most appropriate version of .net?

For now I'm fine with either, just wanting to understand the intent

**Comment by hansenms** [comment]
@marrobi is it better to just remove the file?

**Comment by marrobi** [comment]
That works too! Done.

**Pull request merged**
