### PR TITLE
Fix cosmos iterating over pages of resources

### PR DESCRIPTION
**Pull request by feordin**
## Description
Fix logic surrounding results which are larger than the desired total count.  This caused missing results when paging across results.

## Related issues
Addresses [issue #1898].

## Testing
New E2E tests were added and run.

## FHIR Team Checklist
- [X] **Update the title** of the PR to be succinct and less than 50 characters
- [X] **Add a milestone** to the PR for the sprint that it is merged (i.e. add S47)
- [X] Tag the PR with the type of update: **Bug**, **Dependencies**, **Enhancement**, or **New-Feature**
- [X] Tag the PR with **Azure API for FHIR** if this will release to the managed service
- Review [squash-merge requirements](https://github.com/microsoft/fhir-server/blob/master/SquashMergeRequirements.md)

### Semver Change ([docs](https://github.com/microsoft/fhir-server/blob/master/docs/Versioning.md))
Patch|Skip|Feature|Breaking (reason)
Skip

### CODE REVIEW

**Review by johnstairs — APPROVED** [review]

**Review by CaitlinV39 — APPROVED** [review]
Approving based on John's approval :)

**Comment by Ivanidzo4ka** [comment]
>             int totalDesiredCount = feedOptions.MaxItemCount.Value;

move it to the start of function, it can be overriden by running line 403 to be int.maxValue.

---
Refers to: src/Microsoft.Health.Fhir.CosmosDb/Features/Storage/CosmosFhirDataStore.cs:418 in 5ba3e05. [](commit_id = 5ba3e05ee32bc2d2b2462ac2af2bcb429d7ebcf1, deletion_comment = False)

**Review by Ivanidzo4ka — APPROVED** [review]
:shipit:

**Review by brendankowitz — APPROVED** [review]
When this is merged we should trigger a release

**Comment by feordin** [comment]
> When this is merged we should trigger a release

@brendankowitz , I will make sure and trigger the release.

**Pull request merged**
