### PR TITLE
Update Thirdpartynotices

### PR DESCRIPTION
**Pull request by namadabu**
## Description
Update versions of third party libraries used in the codebase.

## Related issues
Addresses [issue #].

## Testing
No functional change

## FHIR Team Checklist
- [ ] **Update the title** of the PR to be succinct and less than 50 characters
- [ ] **Add a milestone** to the PR for the sprint that it is merged (i.e. add S47)
- [ ] Tag the PR with the type of update: **Bug**, **Dependencies**, **Enhancement**, or **New-Feature**
- [ ] Tag the PR with **Azure API for FHIR** if this will release to the managed service
- Review [squash-merge requirements](https://github.com/microsoft/fhir-server/blob/master/SquashMergeRequirements.md)

### Semver Change ([docs](https://github.com/microsoft/fhir-server/blob/master/docs/Versioning.md))
Patch|Skip|Feature|Breaking (reason)

### CODE REVIEW

**Comment by Ivanidzo4ka** [comment]
This feels like Sisyphean Task.  depenabot would make this file irrelevant in a blink of a eye. Are versions for libraries actually necessary?

**Comment by namadabu** [comment]
> This feels like Sisyphean Task. depenabot would make this file irrelevant in a blink of a eye. Are versions for libraries actually necessary?

I don't know whether the version is a hard requirement. Would also prefer just referring to the library names if that is enough. @brendankowitz @CaitlinV39 thoughts?

**Comment by brendankowitz** [comment]
There is a generated licenses file from [component governance](https://microsofthealth.visualstudio.com/Health/_componentGovernance/47646?_a=components&typeId=5886590&alerts-view-option=active) now, and also a Build Task. I'll check the backlog, ideally we could leverage these

**Comment by brendankowitz** [comment]
Additionally, we should be copying this file into the root of our docker container too :)

**Review by brendankowitz — APPROVED** [review]

**Pull request merged**
