### PR TITLE
Feature/iterate cyclic unsupported

### PR DESCRIPTION
**Pull request by limorl**
## Description
This PR is a continuation of https://github.com/microsoft/fhir-server/pull/1314.
It addresses two cases:

1. Cyclic include iterate queries - which are not supported.
   That is, include iterate queries that include a (transitive) cycle. For example, in this query the parameter _include:iterate=DiagnosticReport:patient produces what Patient:general-practitioner consumes: 
`/MedicationDispense?_include=MedicationDispense:prescription&_include:iterate=MedicationRequest:patient&_include:iterate=Patient:general-practitioner&_revinclude:iterate=DiagnosticReport:performer:Practitioner&_include:iterate=DiagnosticReport:patient&_id=12345`
2. Include Iterate parameters with Circular Reference - which according to the spec results in multiple iterations and up to the implementer to decide how many. We implement it with one iteration and the  For example, in this query, 'partof' reference is os type Organization:
`Organization?_include:iterate=Organization:partof`
  
## Related issues
Addresses #1313

## Testing
1. Unit tests in IncludeRewriterTests to assert that exception is thrown for cyclic queries
2. E2E tests in IncludeSearchTests to assert that for a include iterate parameters with circular reference, the iteration is executed once and an informational issue is added to indicate that

### CODE REVIEW

**Comment by limorl** [comment]
@johnstairs I've given it some thought,  I think we should consider relaxing the exception on Cyclic include iterate queries and take a similar approach to circular reference. That is if a cyclic (transitive) query exists, we can execute is it once, the order of the loop is based on the original query, and then provide informational issue as an operation outcome.
It's basically similar to circular reference, only a transitive recursion, so why not execute one iteration?
WDYT?

**Comment by limorl** [comment]
@LTA-Thinking Looks like Cosmos E2E tests fail, even though the changes are related to SQL only.
There are also failures due to tests running more than 60 minutes.
Is this an environment issue?

**Comment by LTA-Thinking** [comment]
@limorl It looks like some flaky tests. I'm rerunning them and will keep an eye on it.

**Comment by limorl** [comment]
> @limorl It looks like some flaky tests. I'm rerunning them and will keep an eye on it.

Thanks a lot!

**Review by johnstairs — APPROVED** [review]

**Comment by johnstairs** [comment]
Thanks @limorl!

**Pull request merged**
